version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    container_name: postgres
    image: "postgres:12.4"
    env_file:
     - './.env.prod'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: foodgram
    build:
        context: .
        dockerfile: Dockerfile
    image: '33389/foodgram:v1.1'
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    expose:
      - 8000
    env_file:
      - './.env.prod'
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: '33389/foodgram:v1.1'
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static/
      - media_volume:/usr/src/app/media/
    ports:
      - 8000:80
    depends_on:
      - web
